# config/save-world.yml
- hosts: minecraft
  become: true
  tasks:

    #debug START
    - name: Debug - check for save files
      shell: |
        cd /home/ec2-user/minecraft
        ls -a
        cd /spacelift-world
        ls -a
    #debug END
    
    - name: Zip Minecraft world directory
      shell: |
        cd /home/ec2-user/minecraft && zip -r world.zip spacelift-world || true

    - name: Upload zipped world to current S3 bucket
      shell: |
        aws s3 cp /home/ec2-user/minecraft/world.zip s3://{{ lookup('env', 'S3_BUCKET') }}/world.zip
