# config/save-world.yml
- hosts: minecraft
  become: true
  tasks:

    #debug
    - name: Debug - check for save files
      shell: |
        cd /home/ec2-user/minecraft
        ls -a
        cd /world
        ls -a

    #debug
    - name: Zip Minecraft world directory
      shell: |
        cd /home/ec2-user/minecraft && zip -r world.zip spacelift-world || true

    - name: Upload zipped world to current S3 bucket
      shell: |
        aws s3 cp /home/ec2-user/minecraft/world.zip s3://{{ lookup('env', 's3_bucket') }}/world.zip